#############################################################################
# Makefile for building app
# Generated by tmake at 10:23, 2002/10/04
#     Project: app
#    Template: app
#############################################################################

####### filib++ definitions
FIDIR   =       /iwi200/home/users/simon/lib/filib

####### Compiler, tools and options

CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -Wall -W -O2 -DNO_DEBUG
CXXFLAGS=	-pipe -Wall -W -O2 -DNO_DEBUG
INCPATH	=	-I$(QTDIR)/include -I$(FIDIR)/include
LINK	=	g++
LFLAGS	=	-L$(FIDIR)/lib -Wl,-rpath=$(FIDIR)/lib
LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt -lXext -lX11 -lm -lfi -lieee

MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	metaballs.h \
		solver.h \
		surface.h \
		tracer.h 
SOURCES =	main.cpp \
		metaballs.cpp \
		solver.cpp \
		tracer.cpp 
OBJECTS =	main.o \
		metaballs.o \
		solver.o \
		tracer.o 
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	app
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake:
	tmake app.pro

dist:
	$(TAR) app.tar app.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) app.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

main.o: main.cpp \
		metaballs.h \
		surface.h \
		solver.h \
		tracer.h 

metaballs.o: metaballs.cpp \
		metaballs.h \
		surface.h

solver.o: solver.cpp \
		solver.h \
		surface.h

tracer.o: tracer.cpp \
		tracer.h \
		surface.h

